### ISSUE TITLE
Trouble installing RNV package globally on Windows 10.  Using the 'rnv' command from where you want & Missing xcode module exception

### ISSUE THREAD

**Issue by ghost** [pavjacko/renative#322]
**Purpose**
Describing two issues (with solutions) I noticed installing ReNative (RNV) on Windows 10. This is contrary to my experience on macOS Mojave 10.X, which if memory serves, went quite a bit smoother. ... This is to be expected. After reading through the repo history a bit it's clear RNV was created for the Mac initially.

**NOTE** 
- Any reference to the Command Prompt should be ran as an Administrator

**1st Issue** 
- The command `rnv` doesn't automatically become part of the system environment variables. In other words, unable to use `rnv` command in any given directory after globally installing with NPM.  

**Solution** 
I'm on Windows 10 so NPM was automatically installed in AppData\Roaming, i.e., `C:\Users\Kevin.KTUltrabook.001\AppData\Roaming\npm`. The username folder will obviously variate. If that's not where NPM is located, you can search for "npm" in Explorer. -- Once you've found the npm folder, in it you should see a number of files plus the one we're looking for, `rnv.cmd`. -- Go ahead and open a command prompt to the npm folder and try typing `rnv`. You may notice an exception or two that asks for missing libraries. Install globally what it asks for. Unfortunately I'm unable to remember which libraries were missing exactly, but there wasn't many. At this point you'll most likely be running into the second issue. See below. For now I'll finish describing how to run the `rnv` command from any directory.

**1st Solution Continued**
Type "system environment variables" into the Windows search. --> Click the "Edit the System Environment Variables" option. Double click "Path" variable in the System variables pane. --> Click New --> Enter the path to the npm folder, i.e., `C:\Users\Kevin.KTUltrabook.001\AppData\Roaming\npm`. -- No need to restart anything besides your terminal to gain access to the `rnv` command.

**2nd Issue**
- Running `rnv` produces "Error: Cannot find module 'xcode'" build exception

**Solution**
You'll see a stack output that results in the `...\AppData\Roaming\npm\node_modules\rnv\dist\platformTools\apple\xcodeParser.js` file having a missing module. After the stack output you should see a single line saying, "code: 'MODULE_NOT_FOUND'," followed by the requireStack output which lists the xcodeParser.js file for a second time. -- Easy fix as it turns out. -- Go into the xcodeParser.js file and change line 31, which should be `var xcode=require('xcode');` to simply, `var xcode;`. 
- With the exception of the iOS and tvOS targets, RNV should now successfully install anywhere on your machine.

Explanation: One can only use Xcode on an Apple machine thus a Windows machine is unable to find the xcode module.

**Comment by mihaiblaga89** [comment]
First, thank you for the extensive testing.

1. How did you installed node? Regular installer from their website? Using that I had no issues with the PATH when I was testing windows support, but I'll have another go at it. Windows is pretty bad at managing the PATH and it's pretty hard to install something with the terminal and reload the PATH for that terminal so that you can use it.

2. `platformTools/{platform}` is in the process of migration. It will be separate and only installed for platforms that you use and your OS supports. I will do a quick fix for this since it shouldn't crash until then.

**Comment by mihaiblaga89** [comment]
@kevintesar regarding the `xcode` error, what version of RNV were you using and what command did you tried when you saw the error? Just tested latest version, `0.27.6-alpha.3` and I was able to create a new project and run web and android on windows 10 without seeing the `xcode` error

**Comment by kevinbtesar** [comment]
You guys are most welcome! Due to my hectic schedule I've been unable to uninstall npm on my windows machine and start a project from scratch as originally promised, however, I have news that may have rendered that plan moot anyway. 

After updating npm and my global packages on my mac I started a new rnv project. Not thinking too much about it I installed the latest alpha version of rnv. I ended up getting the same missing xcode module build error that happened on windows, so it must of been something about the latest alpha version of that point. That was around 3 or 4 days ago so it's certainly not the alpha you guys are on now. 

I guess what this all boils down to is that the 2nd issue and the resulting resolution were due to my not following the basic protocol of refraining from using an alpha version for production. Anyway though, all that I can hope is that the first issue and solution I described will help someone in the future. 

Guys, feel free to conclude this thread. I'm at a great point with my projects and though I haven't tried your latest alpha, I know you're doing amazing work. Please keep it up! You're doing more for the multi platform dev community than even PhoneGap ever did. :D Take care you guys! 

Best Regards,
-Kevin
