### ISSUE TITLE
react-native vs renative

### ISSUE THREAD

**Issue by SaeedZhiany** [pavjacko/renative#336]
I know renative is based on react-native but I'm wondering why this framework does not merge into the react-native repository and maintain in one place?

Regardless of supporting platforms, is there any difference between these two repositories among Android and IOS? If I have a react-native project, can I migrate it to renative to support more platforms?

**Comment by pavjacko** [comment]
@SaeedZhiany that's a good question! 
you can think of renative as universal development platform which utilises react-native as its core engine for rendering and exposes all of its functionality while enhancing build infrastructure, templating, plugin management and of course support for extra platforms not supported natively by react-native.

however for ios and android platforms you are essentially running react-native project (with slightly different project structure). if you create new hello world rnv project and make first run just check `platformBuilds/helloWorld_ios` and you find pretty much standard react native xcode project

because of that your react-native project can be migrated to renative with minimal amount of changes and even migrated away if desired
for more info check https://renative.org/docs/migrating_react_native
depending on the complexity of your project you can run in under multiple platform pretty much straight away (although you need to pay attention to UX differences like navigation structure, focus management etc) 

if you have issues feel free to comment here for more help

**Comment by SaeedZhiany** [comment]
@pavjacko 
Thank you for your clarification, So merging with React-Native project is not in your repository plan, right?

I suggest to add your explanation somewhere is `README.md` file, it helps a lot for other users want to use this repository and have a question about the difference between these two repositories like me, what do you think?
