### ISSUE TITLE
I cannot run the HelloWorld project on my IOS device

### ISSUE THREAD

**Issue by dassiorleando** [pavjacko/renative#404]
Hi guys,

When I'm starting a helloworld project all is well till I try to run it into my IOS device, maybe it's something related to react-native update I'm not sure.

**Commands I ran:**
- rnv start
- rnv run -p ios -s ad-hoc -d (my device is connected of course)

**Here's the output:**
$ rnv run -p ios -s ad-hoc -d - ERRROR! COMMAND: 

react-native run-ios --project-path /Users/path/rnv1/platformBuilds/helloWorld_ios --device --udid 6d1f079a28aab8cf53a020a1399a92ff1a642b03 --scheme RNVApp --configuration Release 

FAILED with ERROR: 

error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
 - react-native-gesture-handler (to unlink run: "react-native unlink react-native-gesture-handler")
 - react-native-reanimated (to unlink run: "react-native unlink react-native-reanimated")
 - react-native-vector-icons (to unlink run: "react-native unlink react-native-vector-icons")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening RNVApp.xcworkspace. Run CLI with --verbose flag for more details.

Do you know how to handle this, please?
Regards,

**Comment by pavjacko** [comment]
@dassiorleando it helps if you can post whole "summary" box output from your console. that way I know what version, env you running helps solving issues faster. 

that's box which starts with ` 🚀  SUMMARY ....`

annoyingly `error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:`
is not real issue rather than "red herring". looking into way how to remove this error which is actual warning really.

but back to your issue:

for now I'll assume you running renative `0.28.17`

this issue is usually related to provisioning profiles, certificates or your team ids not being setup correctly 
fortunately it is easy to check. rnv generates standard xcode project so you can open it and run it directly from there for more in depth analysis

first thing to do in such a cases is to simply open 
`/Users/path/rnv1/platformBuilds/helloWorld_io/RNVApp.xcworkspace`
in actual xcode and simply run your project from there

if you have provisioning issues xcode could offer you to fix them automatically including adding your device to prov profile list etc

try that first and post if it helped or your issues persist

**Comment by dassiorleando** [comment]
@pavjacko you are right Thanks, the error at the end is:

 **No profiles for 'com.domain.rnv1' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.domain.rnv1'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'RNVApp' from project 'RNVApp')**
