### ISSUE TITLE
Using SVG libraries with renative

### ISSUE THREAD

**Issue by ix42** [pavjacko/renative#418]
Hi, i am trying to use react-native-svg and svg-inline-react with renative. It works fine as a web app, but when deploying to an android device i get an error like below.
Do i need to add to add plugins for these packages? If yes, is there a tutorial that could guide me?
Thank you.

Invariant Violation: Invariant Violation: Invariant Violation: requireNativeComponent: "RNSVGPath" was not found in the UIManager.

This error is located at:
in RNSVGPath (at Path.js:17)
in Path (at animated-path.js:72)
in AnimatedPath (at progress-circle.js:108)

**Comment by mihaiblaga89** [comment]
you will need to _tell_ `rnv` to inject those native components inside the app. 

For `react-native-svg`, which is directly supported by `rnv`, all you need to do is run `rnv plugin add` and select it from the list (https://renative.org/docs/plugins). For packages that are not in that list you'll need to follow https://renative.org/docs/plugins#custom-plugin-support

From what I can see `svg-inline-react` is for React web. I think you'll only need `react-native-svg` since `react-native-web` that is used behind the scenes for web will do it's job and display that on web as well.
