### ISSUE TITLE
Video component can't find resolveAssetSource from react-native

### ISSUE THREAD

**Issue by franco948** [pavjacko/renative#443]
I'm trying to use the **react-native-video** library as a plugin with the command `rnv plugin add`.

When I import the `Video` component from react-native-video I get the following error:

```
ERROR in ./node_modules/react-native-video/Video.js
Module not found: Error: Can't resolve 'react-native/Libraries/Image/resolveAssetSource' in 'C:\dev\ReNativePlayGround\node_modules\react-native-video'
 @ ./node_modules/react-native-video/Video.js 4:47-105
 @ ./src/app.js
 @ ./index.web.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./index.web.js
```

I already took a look at the **node_modules** folder and the files are in place.

I've created a project with the blank template provided by `rnv new` command and testing the application with the browser and Tizen emulator.

**Comment by mihaiblaga89** [comment]
@franco948 `react-native-video` is for ios/android only. Tizen is web-based, so you should use a web-based player, like ShakaPlayer, since apparenty `react-native-web` does not have support for that `Image/resolveAssetSource`. Then you can create your own Video component that uses one or the other, based on the platform. To do that you can leverage the `rnv` file extensions to create `Component.web.js` and `Component.native.js`

**Comment by franco948** [comment]
Thanks for the answer!. I am gonna try with another player then.
