### ISSUE TITLE
Develop branch Web target build failure

### ISSUE THREAD

**Issue by elmpp** [pavjacko/renative#501]
**Describe the bug**
Running `rnv run -Rp web` fails

**To Reproduce**
Tested against last develop of `sdk-ui` project, local checkout of develop (committish '4032d2fa86fc80de3df1b7dcc652b8c85c6e4230') gives this result https://hastebin.com/ucozugohak .  Have not tested against alphas

**Expected behavior**
A stable develop branch

**Screenshots or copy&paste**
https://hastebin.com/ucozugohak

**Desktop (please complete the following information):**
https://hastebin.com/ucozugohak

**Comment by pavjacko** [comment]
@elmpp 
tested and looks fine to me. (tested against original `0.29.0-alpha.34` and latest `0.29.1-alpha.5`
you are running project with your local linked version or rnv.

can you test it with `npx rnv run -Rp web` first

if you do try to run with latest rnv your `platformBuilds/..._web/webpack.extend.js` should have this snippet present:

```
"moduleAliases": {
    "react-native-gesture-handler": {
      "path": "react-native-gesture-handler"
    },
    "react-native-vector-icons": {
      "path": "react-native-vector-icons"
    }
  },
```

otherwise something wrong with your local rnv

**Comment by elmpp** [comment]
After doing a `git clean -fdx` i can't reproduce anymore. Apologies, closing.

Does `-R` reset all rnv artifacts or just platformBuilds? Would be nice if it really regenerated everything
