### ISSUE TITLE
How can we check arrow events in android tv and how can we restrict a focus in a particular button in Android TV?

### ISSUE THREAD

**Issue by SandeepKharbanda** [pavjacko/renative#504]
Hi,

I am developing an application in Android TV. But, I am unable to find the arrow events when the user presses arrow buttons. So, How can we check left, right, top, and bottom arrow events in Android TV and how can we restrict a focus in a particular button in Android TV?

**Comment by aurimasmi** [comment]
If I understood you correctly to handle controller events you need https://reactnative.dev/docs/building-for-tv just instead of 
`var TVEventHandler = require('TVEventHandler');`  as described in docs use:  `import { TVEventHandler } from 'react-native'`

Only one proper way to disable focus is use `<View />`(or another non focusable element)  instead of `TouchableOpacity`. 
Also there is a prop called `disabled` for `TouchableOpacity` which disables interactions for that element, but behind the scenes it's still focusable.

**Comment by SandeepKharbanda** [comment]
@aurimasmi : Yes, I did it in the same way but thought, It's a hack. So, I was considering, is there any better solution for it?
`if(disabled){
            return(
                <View 
                    style={style}>
                    {children}
                </View>
            )
        }

        return (
            <TouchableOpacity
                style={style}
                disabled={disabled}
                activeOpacity={activeOpacity}
            >
                {children}
            </TouchableOpacity>
        );
`

**Comment by EyMaddis** [comment]
Short answer: you can't. Android handles the focus mangement in native code, you cannot really control focus in JS, except for manually setting the focus to something (or with hacks such as above). 
You cannot block key presses without completely disabling all key events in Java and manually writing a focus engine in JS.
In the time the message from the keypress reaches JavaScript, Android is already doing its thing...
