### ISSUE TITLE
Make Override System Portable

### ISSUE THREAD

**Issue by elmpp** [pavjacko/renative#537]
**Is your feature request related to a problem? Please describe.**

It would be very beneficial if RNV's override system was more standardised and could be applied via other methods. 

On the most part this is ok for building static deployables (which can then be deployed independently) but presents a problem when runtime dependencies are in need of patching also (i.e. Next)

An example concrete use case would be [building Docker containers](https://github.com/24i/prd-nxg-sdk-ui/pull/159#discussion_r450215420)

**Describe the solution you'd like**

A probable format here would be git diffs. Example uses of this are [patch package](https://github.com/ds300/patch-package), [git apply](https://git-scm.com/docs/git-apply) or even [yarn2's patch protocol](https://yarnpkg.com/features/protocols)

Creating the patches would be much easier also via `git diff` etc

**Describe alternatives you've considered**

For our specific use case contributing upstream to Next [isn't an option](https://github.com/vercel/next.js/issues/4315#issuecomment-526832636). This proposal is obviously more generic however

**Comment by pavjacko** [comment]
@elmpp yes, as rnv plugin support grows, more robust override system will be needed. especially when it comes to
 
- versioning
- diffing / patching
- compiled files overrides 
- dist regeneration

standard RN plugins are not affected as badly due to their simplicity and non compiled code nature and so it was generally manageable. nextjs is much bigger beast. forking was proven not viable either.

we investigated this before and https://github.com/ds300/patch-package should be good starting point

target for such a feature is around `0.32.x` after 1st phase of engine introduction (`0.31.x`)
