### ISSUE TITLE
Integrating RNV apps with Sentry

### ISSUE THREAD

**Issue by AndrejJurkin** [pavjacko/renative#559]
I’m trying to add Sentry lib to our RNV projects. https://docs.sentry.io/platforms/react-native/manual-setup

I tried adding the following lines into renative.json

```
    "@sentry/react-native": {
      "version": "1.7.1",
      "ios": {
        "podName": "RNSentry"
      },
      "android": {
        "projectName": "@sentry_react-native",
        "path": "node_modules/@sentry/react-native/android",
        "package": "io.sentry",
        "implementation": "implementation project(':@sentry_react-native')"
      }
    },
```
On iOS build crashes after this log:
```
[!] CocoaPods could not find compatible versions for pod "Sentry":
 In snapshot (Podfile.lock):
 Sentry (= 4.1.0)
 In Podfile:
 RNSentry (from `/Users/andrej/Projects/react-native/24i/prj-1450-chl/node_modules/@sentry/react-native`) was resolved to 1.7.1, which depends on
 Sentry (~> 5.2.0)
│ 🛑  $ rnv run -p ios -s debug - ERRROR! COMMAND: 
pod update 
FAILED with ERROR: 
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
 In Podfile:
 RNFBApp (from `/Users/andrej/Projects/react-native/24i/prj-1450-chl/node_modules/@react-native-firebase/app`) was resolved to 6.4.1, which depends on
 Firebase/Core (~> 6.13.0) was resolved to 6.13.0, which depends on
 Firebase/CoreOnly (= 6.13.0) was resolved to 6.13.0, which depends on
 FirebaseCore (= 6.4.0)
```
It looks like there is a conflict in Sentry dependencies, 4.1.0 vs 5.2.0 for some reason.

**Any ideas what could be the issue please?**

On Android the setup requires modifying gradle files
[Sentry - Manual setup](https://docs.sentry.io/platforms/react-native/manual-setup/#android)

```
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
project.ext.sentryCli = [
    logLevel: "debug"
]
project.ext.sentryCli = [
    logLevel: "debug",
    flavorAware: true
]
```
**Any idea how to add these?**

On Android it crashes with the following log:
```
> Task :app:compileDebugKotlin FAILED
e: /Users/andrej/Projects/react-native/24i/prj-1450-chl/platformBuilds/chl_android/app/src/main/java/rnv/MainApplication.kt: (36, 11): Packages cannot be imported
e: /Users/andrej/Projects/react-native/24i/prj-1450-chl/platformBuilds/chl_android/app/src/main/java/rnv/MainApplication.kt: (82, 1): Unresolved reference: sentry
FAILURE: Build failed with an exception.
```

**Comment by pavjacko** [comment]
@AndrejJurkin this usually happens if you have 2 conflicting pods. each of them referencing different version of specific dependency (in your case (Sentry) in their respective podspecs. 

You need to fix one of these dependencies so you use same version.

There is one alternative way how to quickly test switching to same version of dependency via RNV overrides.

NOTE: this alternative is possible only if following applies:
- you sentry upgrade does not require actual changes in code in one of your dependency. if yes this might not be enough
- this dependency is npm based.

You can override whole podspec of your sub dependcency via :

`./appConfigs/base/plugins/[PLUGIN]/overrides/[pluginpodspec.podspec]`
