### ISSUE TITLE
Focus not working in Android Tv Boxes

### ISSUE THREAD

**Issue by sandarshnaroju** [pavjacko/renative#581]
I'm currently working on a android tv project with renative. Focus is working fine in emulator but not in `android Tv` boxes. 

It looks similar to this https://www.flipkart.com/sreetek-android-9-0-tv-box-tx6-4gb-32gb-4k-wifi-bluetooth-media-streaming-device/p/itm5cfcd613f5932.
`onFocus` and `onBlur` are not being called when using with android Tv box. However, it is working fine in emulator.

How should I get it to work?

**Comment by RicardasN** [comment]
Are you using those methods on a TouchableOpacity? Because a view or other non-focusable component does not support these functions. I had been using Xiaomi MiBox 4, Nvidia Shield and these functions work as expected. The only thing I can come up with, that could be wrong is the component you're calling these functions on.

**Comment by sandarshnaroju** [comment]
Yes, I am using `TouchableOpacity`. But `onFocus` and `onBlur` are not getting called in `Android Tv` Box.

**Comment by iMokhles** [comment]
@sandarshnaroju do you use react-native-keyevent package ?
