### ISSUE TITLE
Google Signin / Login WebOS

### ISSUE THREAD

**Issue by AkAyush** [pavjacko/renative#634]
Hi, I was tyring to implement Google Signin in WebOS. I have used 'react-google-login' for it the same library I'm using for Web. But WebOS is not allowing google signin popup window to appear.

Has anyone implemented Google Signin in WebOS? Please let me know

**Comment by TheDuc** [comment]
Hey AkAyush,

'react-google-login' is a library for React, not React-Native. ReNative uses React-Native and React-Native-web to convert native components to web for for example WebOS. I believe you have to use a React-Native Google Signin library, for example [@react-native-community/google-signin](https://www.npmjs.com/package/@react-native-community/google-signin) instead of a React only library. Hope that helps!

**Comment by EyMaddis** [comment]
Since WebOS is "web" based, @react-native-community/google-signin will never work. SmartTVs cannot open new windows. You will most likely never be able to implement Google Sign in with the default way.
You will have to implement a code based login (which Google seems to support 🎉 ):
 https://developers.google.com/identity/sign-in/devices

It basically does not use mail + password, but a single generated code instead that the UI shows and the user has to enter with another device.

I never implemented it myself, so that is all I can help you with, but please don't run down the path of trying email+password login in a smart TV app.
