### ISSUE TITLE
Help with ReNative components documentation

### ISSUE THREAD

**Issue by chmiiller** [pavjacko/renative#635]
Hi there,
first of all thanks for all that is offered with ReNative!

I'm working on a Tizen personal side project focused on Samsung TVs and having a lot of fun with it but maybe I'm missing out some information about ReNative that I really would like to clarify.

I noticed that when I start a new project with rnv it comes with some plugins like the "NoriginMedia/react-spatial-navigation" and other nice libs like fonts and icons for example. I've also noticed that it comes with some other renative components like a Button for example. So my question is, what are the exact differences between **renative** components and **react-native** components? Why should I use ReNative's StyleSheet instead of React-Native's one? What does `usePop` do?  What does `Api` returns? When can I use `useOpenDrawer` on my app? 
And more important, what else is included on `renative` package? Maybe I can implement a lot of another cool features on my app that I'm missing out or implement stuff in a easier way.

I know that a Button from ReNative is much more feature-packed but I cannot find a documentation with all these extra properties, is it available somewhere?
I've also found that ReNative uses react-native-web components but I don't know if I should trust these docs for my rnv app.

Can someone help me to better understand this? Sorry if this is not the correct place to ask about it but I couldn't think of somewhere else.

Thanks!

**Comment by pavjacko** [comment]
Hi @chmiiller 

--
differences between renative components and react-native components

renative focus is more towards unified infrastructure and multi-platform fundamentals by combining variety of OS libraries under one hood (ie react-native, electron, rn web etc)

General purpose of `renative` runtime library is to provide base abstraction and helper methods  ie `isPlatformTizen` , `isFactorTv`  etc.  

renative's "Button" component is an minimalistic example of how multi-platform UI component can exist in such an environment.

If the would ever be a true multiplatform UI (component) library it will be outside of `renative` library

--
What does usePop do? What does Api returns? When can I use useOpenDrawer on my app? 

these hooks are another example of multiplatform abstraction in this case, navigation.

`renative-template-hello-world` showcase the use this abstraction.

but again it is very simplistic and is used more as guideline to build you own navigation. remember there are infinite amount of combinations of different libraries and approaches you could take to build your app. I wanted to avoid for renative to dictate what libs / architecture to use as much as possible. this quite minimalistic approach to UI for example

--
Why should I use ReNative's StyleSheet instead of React-Native's one?

this basic abstraction utility which uses RN's StyleSheet when standard RN engines but switches to basic object if you using next engine (next does not support StyleSheet)

--
renative is still under active development. I'm trying to make docs more robust. and also keep evolving based on community feedback!

Hope this answered some of your questions but feel free to ask more :)

**Comment by chmiiller** [comment]
Thanks for clarifying all of this! It does make sense, can't wait to see these developments and more examples.
