### ISSUE TITLE
Cannot connect to the device with adb over wifi

### ISSUE THREAD

**Issue by d4rky-pl** [pavjacko/renative#699]
**Describe the bug**
When running `rnv run` it kills the `adb` server and restarts it again. This clears any devices that are connected remotely.

**To Reproduce**

1. Enable adb over wifi on your device
2. Find the IP to the device and connect with `adb connect x.x.x.x:5555`
3. Run `rnv run -p androidwear -d`

**Expected behavior**
It should connect to the available device instead of ignoring it and asking about the emulator

**Screenshots or copy&paste**

```
[ task ] [run] runAndroid[1] target:192.168.0.52:5555 default:192.168.0.52:5555
✔ Executing: /Users/matyas/Library/Android/sdk/platform-tools/adb kill-server
✔ Executing: /Users/matyas/Library/Android/sdk/platform-tools/adb start-server
[ task ] [run] getAndroidTargets[1] skipDevices:false skipAvds:false deviceOnly:true
✔ Executing: /Users/matyas/Library/Android/sdk/platform-tools/adb devices -l
✔ Executing: /Users/matyas/Library/Android/sdk/emulator/emulator -list-avds
[ task ] [run] composeDevicesString[1] numDevices:1
? What emulator would you like to start?
❯ Android_Wear_Round_API_28 | Wear ⌚  | arch: x86 | udid: unknown
```

**Desktop (please complete the following information):**

-   OS: osx
-   Node Version: v12.16.3
-   RNV Version: 0.32.0-alpha.45

**Comment by mihaiblaga89** [comment]
that most likely happens because rnv thinks your watch is a phone. Support will need to be added for that device if it's one which doesn't advertise itself as being a watch in the common properties that rnv checks. Would be nice if you could send us the output of `adb devices -l` and maybe `adb -s <ID> shell getprop` so we can add it. In the meantime you could skip the device decision making part with `--skipTargetCheck`

**Comment by d4rky-pl** [comment]
@mihaiblaga89 FYI: I have this email pinned in my inbox and I promise I'll deliver you more information but I stopped using my TicWatch 3 Pro and removed ReNative months ago so I'll have to wait for the weekend to set everything up again and get you more context.

As for RNV thinking my watch is a phone, I do remember applying [a patch](https://github.com/pavjacko/renative/pull/666) manually to ensure that my watch is detected properly as a watch (it didn't work at all otherwise) so I don't believe that was the reason for the problem.

**Comment by mihaiblaga89** [comment]
Oh yeah, that was merged. Then I think I can consider this issue closed if that patch was working for you. Otherwise if you still encounter this issue feel free to reopen it. If you get the chance to send us more info about the device by running the commands specified above we would greatly appreciate it.

**Comment by d4rky-pl** [comment]
@mihaiblaga89 the patch was not working for me which is why I opened the issue in the first place
